Day Class Reference
#include <day.h>
Detailed Description
The day class is used for the following reasons:
Hold statistical information for the participations daily.
Hold the array of prizes to be given daily.
execute the actual draw of the competition, that is decide whether this participation wins or not, and what.
 There are three possible ways to create a Day object, using three possible constructors. The first Day() is just a dummy constructor that just creates an empty shell to be populated later. It is not usable. The second takes a string representation of a Day's details, actually the result from an SQL SELECT command in the COUNTERS table, so that it can construct the Day again. It's only used in statistics. The third constructor, takes the time period, a flag to signify whether we are at the start of a new week or month, and performs the following actions:
Estimate the number of the participations for the particular day.
Assign the prizes in fixed positions in an array that holds the messages.
provide a method to be called from the Processor object, to execute the actual draw of the competition.
 The class Day is also used as a template class for SQLTable<>. For this reason, we have created two methods insertString() and updateString(), that return the daily counters as strings representations, to be used in the insert* and update* SQLTable methods respectively. About the DayMessages vector: This one has a `current index` variable, a cursor, that moves forward one position for each participation. At the start of the day, this vector is cleared and resized to hold the estimated messages for this day. For each participation, it picks the value at the current position and returns it to the participant. The value is either 0 (for no prize), or the id of the prize itself.
Definition at line 63 of file day.h.
Public Methods
Day (class Contest *myContest, TimeStamp &ts)
The class constructor.
Day (string daystr)
Class constructor for SQLTable<> support.
Day ()
dummy constructor that just creates an empty structure
TimePeriod getTimePeriod ()
return the current day TimePeriod object
void setTimePeriod (TimePeriod &tp)
Sets the time period.
void assignPrizes ()
Assign the prizes to the DayMessages.
u_int calculateEstNoMsgs ()
Calculate estimated Number of Messages for this day.
u_int getEstNoMsgs ()
Return estimated Number of Messages for this day.
bool executeDraw (partDetails &pd)
Execute draw for the given partDetails object.
void setCounter (u_int &val)
Set counter.
u_int getCounter ()
return counter
u_int getUniqueCounter ()
return unique counter
u_int getNoPrizes ()
return no of prizes
string insertString ()
This is for the SQLTable<> template class.
string updateString ()
This is for the SQLTable<> template class.
bool isEmpty ()
boolean method to be used in SQLTable<> methods
Private Types
enum { default_avg_threshold = 5
 }
An enumerator object for the calculation of the estimated number of messages.
enum { default_estNoMsgs = 10000,
min_estNoMsgs = 1600
 }
Enumeration objects for the default and minimum number of est. number of messages.
Private Attributes
Contest * parentContest
A pointer to the Contest part of which is this.
vector< u_int > DayMessages
The vector that holds the Prizes that are given to the participants.
Count counter
Counter of the current number of participants.
Count unique_counter
The unique players for today.
u_int estNoMsgs
The estimated number of messages for this day.
u_int prizes
The number of prizes won so far in the current day.
TimePeriod day_period
The current day period.
bool empty
boolean for SQLTable<> template class
Friends
class Processor
The Processor is a friend class and can access the private members of Day.
Member Enumeration Documentation
anonymous enum [private]
Enumeration values:
default_avg_threshold
Definition at line 66 of file day.h.
anonymous enum [private]
Enumeration values:
default_estNoMsgs
min_estNoMsgs
Definition at line 69 of file day.h.
Constructor & Destructor Documentation
Day::Day (class Contest * myContest, TimeStamp & start_ts)
The Day constructor. It takes the Contest object pointer, the starting TimeStamp. It estimates the number of messages for the specific time period and resizes the DayMessages vector. Firstly, it checks the COUNTERS table to see if a record for the particular day already exists, and if so, retrieves the counters from the table. Then the system will continue from the previous state. Otherwise it will try to estimate the number of messages for this day using calculateEstNoMsgs(). Whatever the case it will have a valid value for estNoMsgs and will resize DayMessages vector with that size. Then it will assign the available prizes (taking into account the COUNTERS variable prizes) into random positions in DayMessages.
Definition at line 29 of file day.cpp.
References assignPrizes(), calculateEstNoMsgs(), counter, Contest::Counters, day_period, DayMessages, estNoMsgs, TimePeriod::getBeginTS(), getCounter(), getEstNoMsgs(), getNoPrizes(), TimeStamp::getTimeStamp(), getUniqueCounter(), SQLTable< string, Day >::insertObject(), isEmpty(), Contest::logger, Logger::logMsg(), TimeStamp::nextDay(), parentContest, prizes, Count::set(), TimeStamp::toString(), TimePeriod::toString(), and unique_counter.
Day::Day (string daystr)
Take a string representation of the variables in the COUNTERS table, counter, unique_counter, estNoMsgs and prizes, and resets the day, setting the empty boolean to true as well.
Definition at line 75 of file day.cpp.
References counter, empty, estNoMsgs, prizes, Count::set(), strTokenizer(), and unique_counter.
Day::Day () [inline]
Definition at line 105 of file day.h.
References empty.
Member Function Documentation
void Day::assignPrizes ()
assignPrizes() is responsible for attaching a gift to a position in the DayMessages vector. Basically, DayMessages is a vector whose current position will give the next given prize. Since probabilities are floating point numbers and we have to correspond these to gift ids, we have to iterate over all available presents for this day and assign them to the DayMessages vector. Espessially for the weekly and monthly gifts, we don't force them to be assigned in the first n-1 days of their respective periods but we do force them to be assigned in the last day.
Definition at line 103 of file day.cpp.
References Contest::current_month, Contest::current_week, TimePeriod::dateInPeriod(), day_period, DayMessages, Contest::EOM, Contest::EOW, TimePeriod::getBeginTS(), giftDetails::ID_MONTHLYPRIZES, giftDetails::ID_NOGIFT, giftDetails::ID_WEEKLYPRIZES, Contest::logger, Logger::logMsg(), parentContest, TimeStamp::previousDay(), Contest::Prizes, and SQLTable< string, giftDetails >::selectObjects().
Referenced by Day().
u_int Day::calculateEstNoMsgs ()
Calculates an average of the past {default_avg_threshold} days' counters, and returns the result. If the Contest has just started then it returns {default_estNoMsgs}, and if the result of 0.8 * average is less than {min_estNoMsgs} it returns {min_estNoMsgs} instead.
Definition at line 194 of file day.cpp.
References default_avg_threshold, default_estNoMsgs, Contest::getContestDays(), Contest::logger, Logger::logMsg(), min_estNoMsgs, and parentContest.
Referenced by Day().
bool Day::executeDraw (partDetails & pd)
The actual draw engine is here. Given a partDetails object which holds information on the code, the MSISDN, and the timestamp, fill the appropriate gift id in this object. We take the gift id from the current value in DayMessages vector in the position pointed to by counter, if of course, counter is less than the size of DayMessages. If it is bigger, then the prize won is nothing. At the end a check is made to confirm that we don't give extra prizes.
Definition at line 243 of file day.cpp.
References counter, Contest::current_month, Contest::current_week, day_period, DayMessages, Contest::EOM, Contest::EOW, partDetails::getGiftId(), Contest::giftIsGiven(), giftDetails::ID_DAILYPRIZES, giftDetails::ID_HOURLYPRIZES, giftDetails::ID_MONTHLYPRIZES, giftDetails::ID_NOGIFT, giftDetails::ID_WEEKLYPRIZES, parentContest, partDetails::setGiftId(), and Count::val().
Referenced by Processor::process_i().
u_int Day::getCounter ()
Returns the current value of the counter
Definition at line 296 of file day.cpp.
References counter, and Count::val().
Referenced by Day().
u_int Day::getEstNoMsgs ()
Definition at line 183 of file day.cpp.
References estNoMsgs.
Referenced by Day().
u_int Day::getNoPrizes ()
Returns the current value
Definition at line 319 of file day.cpp.
References prizes.
Referenced by Day().
TimePeriod Day::getTimePeriod ()
Definition at line 173 of file day.cpp.
References day_period.
Referenced by Processor::process_i().
u_int Day::getUniqueCounter ()
Returns the current value of the counter
Definition at line 312 of file day.cpp.
References unique_counter, and Count::val().
Referenced by Day().
string Day::insertString ()
returns a string suitable to be used in insert* methods of SQLTable.
Definition at line 328 of file day.cpp.
References counter, estNoMsgs, prizes, unique_counter, and Count::val().
bool Day::isEmpty ()
This is to check if a Day object has been created with the dummy constructor Day().
Definition at line 356 of file day.cpp.
References empty.
Referenced by Day().
void Day::setCounter (u_int & val)
Sets the value of the counter. Used for recovery purposes.
Definition at line 303 of file day.cpp.
References counter, Count::set(), and Count::val().
void Day::setTimePeriod (TimePeriod & tp)
Definition at line 178 of file day.cpp.
References day_period.
string Day::updateString ()
returns a string suitable to be used in update* methods of SQLTable.
Definition at line 342 of file day.cpp.
References counter, estNoMsgs, prizes, unique_counter, and Count::val().
Referenced by Processor::process_i().
Friends And Related Function Documentation
friend class Processor [friend]
Definition at line 78 of file day.h.
Field Documentation
Count Day::counter [private]
Definition at line 81 of file day.h.
Referenced by Day(), executeDraw(), getCounter(), insertString(), Processor::process_i(), setCounter(), and updateString().
TimePeriod Day::day_period [private]
Definition at line 93 of file day.h.
Referenced by assignPrizes(), Day(), executeDraw(), getTimePeriod(), and setTimePeriod().
vector<u_int> Day::DayMessages [private]
Definition at line 75 of file day.h.
Referenced by assignPrizes(), Day(), and executeDraw().
bool Day::empty [private]
Definition at line 96 of file day.h.
Referenced by Day(), and isEmpty().
u_int Day::estNoMsgs [private]
Definition at line 87 of file day.h.
Referenced by Day(), getEstNoMsgs(), insertString(), and updateString().
class Contest* Day::parentContest [private]
Definition at line 72 of file day.h.
Referenced by assignPrizes(), calculateEstNoMsgs(), Day(), and executeDraw().
u_int Day::prizes [private]
Definition at line 90 of file day.h.
Referenced by Day(), getNoPrizes(), insertString(), Processor::process_i(), and updateString().
Count Day::unique_counter [private]
Definition at line 84 of file day.h.
Referenced by Day(), getUniqueCounter(), insertString(), Processor::process_i(), and updateString().
The documentation for this class was generated from the following files:
day.h
day.cpp