Client_Acceptor Class Reference
#include <client_acceptor.h>
Public Types
typedef Client_Acceptor_Base inherited
enum concurrency_t { single_threaded_,
thread_per_connection_,
thread_pool_
 }
Public Methods
Client_Acceptor (Contest *myContest, concurrency_t concurrency=thread_pool_)
Client_Acceptor (Contest *myContest, Thread_Pool &thread_pool)
~Client_Acceptor (void)
int open (const ACE_INET_Addr &addr, ACE_Reactor *reactor, int pool_size=Thread_Pool::default_pool_size_)
int close (void)
int concurrency (void)
Thread_Pool * thread_pool (void)
int thread_pool_is_private (void)
int make_svc_handler (Client_Handler *&ch)
Register the service handler to the acceptor.
void setContest (Contest *curContest)
Set parent contest.
Contest * getContest ()
Get parent contest.
Protected Attributes
int concurrency_
Thread_Pool private_thread_pool_
Thread_Pool & the_thread_pool_
Contest * parentContest
Member Typedef Documentation
typedef Client_Acceptor_Base Client_Acceptor::inherited
Definition at line 54 of file client_acceptor.h.
Member Enumeration Documentation
enum Client_Acceptor::concurrency_t
Now that we have more than two strategies, we need more than a boolean to tell us what we're using. A set of enums is a good choice because it allows us to use named values. Another option would be a set of static const integers.
Enumeration values:
single_threaded_
thread_per_connection_
thread_pool_
Definition at line 60 of file client_acceptor.h.
Constructor & Destructor Documentation
Client_Acceptor::Client_Acceptor (Contest * myContest, concurrency_t concurrency = thread_pool_)
The default constructor allows the programmer to choose the concurrency strategy. Since we want to focus on thread-pool, that's what we'll use if nothing is specified.
Definition at line 7 of file client_acceptor.cpp.
Client_Acceptor::Client_Acceptor (Contest * myContest, Thread_Pool & thread_pool)
Another option is to construct the object with an existing thread pool. The concurrency strategy is pretty obvious at that point.
Definition at line 16 of file client_acceptor.cpp.
Client_Acceptor::~Client_Acceptor (void)
Our destructor will take care of shutting down the thread-pool if applicable.
Definition at line 26 of file client_acceptor.cpp.
References concurrency(), thread_pool(), thread_pool_, and thread_pool_is_private().
Member Function Documentation
int Client_Acceptor::close (void)
Close ourselves and our thread pool if applicable
Definition at line 51 of file client_acceptor.cpp.
References concurrency(), Thread_Pool::stop(), thread_pool(), thread_pool_, and thread_pool_is_private().
int Client_Acceptor::concurrency (void) [inline]
What is our concurrency strategy?
Definition at line 91 of file client_acceptor.h.
References concurrency_.
Referenced by close(), Client_Handler::concurrency(), open(), and ~Client_Acceptor().
Contest* Client_Acceptor::getContest () [inline]
Definition at line 123 of file client_acceptor.h.
References parentContest.
int Client_Acceptor::make_svc_handler (Client_Handler *& ch)
Registers the Client_Handler Reactor to the Acceptor's reactor, while also setting the parentContest object to this->getContest().
Definition at line 63 of file client_acceptor.cpp.
References Client_Handler::setContest().
int Client_Acceptor::open (const ACE_INET_Addr & addr, ACE_Reactor * reactor, int pool_size = Thread_Pool::default_pool_size_)
Open ourselves and register with the given reactor. The thread pool size can be specified here if you want to use that concurrency strategy.
Definition at line 38 of file client_acceptor.cpp.
References concurrency(), Thread_Pool::start(), thread_pool(), thread_pool_, and thread_pool_is_private().
Referenced by Contest::initThreads().
void Client_Acceptor::setContest (Contest * curContest) [inline]
Definition at line 120 of file client_acceptor.h.
References parentContest.
Thread_Pool* Client_Acceptor::thread_pool (void) [inline]
Give back a pointer to our thread pool. Our Client_Handler objects will need this so that their handle_input() methods can put themselves into the pool. Another alternative would be a globally accessible thread pool. ACE_Singleton<> is a way to achieve that.
Definition at line 101 of file client_acceptor.h.
References the_thread_pool_.
Referenced by close(), open(), Client_Handler::thread_pool(), and ~Client_Acceptor().
int Client_Acceptor::thread_pool_is_private (void) [inline]
Since we can be constructed with a Thread_Pool reference, there are times when we need to know if the thread pool we're using is ours or if we're just borrowing it from somebody else.
Definition at line 108 of file client_acceptor.h.
References private_thread_pool_, and the_thread_pool_.
Referenced by close(), open(), and ~Client_Acceptor().
Field Documentation
int Client_Acceptor::concurrency_ [protected]
Definition at line 127 of file client_acceptor.h.
Referenced by concurrency().
Contest* Client_Acceptor::parentContest [protected]
Definition at line 133 of file client_acceptor.h.
Referenced by getContest(), and setContest().
Thread_Pool Client_Acceptor::private_thread_pool_ [protected]
Definition at line 129 of file client_acceptor.h.
Referenced by thread_pool_is_private().
Thread_Pool& Client_Acceptor::the_thread_pool_ [protected]
Definition at line 131 of file client_acceptor.h.
Referenced by thread_pool(), and thread_pool_is_private().
The documentation for this class was generated from the following files:
client_acceptor.h
client_acceptor.cpp