Client_Handler Class Reference
#include <client_handler.h>
Detailed Description
Another feature of ACE_Svc_Handler is it's ability to present the ACE_Task<> interface as well. That's what the ACE_NULL_SYNCH parameter below is all about. That's beyond our scope here but we'll come back to it in the next tutorial when we start looking at concurrency options.
Definition at line 42 of file client_handler.h.
Public Types
typedef ACE_Svc_Handler< ACE_SOCK_STREAM, ACE_NULL_SYNCH > inherited
Public Methods
Client_Handler (void)
Constructor...
void destroy (void)
int open (void *acceptor)
int close (u_long flags=0)
int handle_close (ACE_HANDLE handle, ACE_Reactor_Mask mask)
int handle_input (ACE_HANDLE handle)
void setContest (Contest *curContest)
Sets the parentContest pointer with the given one.
Contest * getContest ()
Returns the parentContest pointer.
Protected Methods
int svc (void)
int process (unsigned char *rdbuf, size_t rdbuf_len)
~Client_Handler (void)
Client_Acceptor * client_acceptor (void)
void client_acceptor (Client_Acceptor *_client_acceptor)
int concurrency (void)
Thread_Pool * thread_pool (void)
Protected Attributes
ACE_Thread_Mutex mutex_
A basic Thread_Mutex class that will ensure safe access to data.
Contest * parentContest
Pointer to the parent Contest object;.
unsigned char * data
Data to hold the connectionMsgBlock object.
int srv_counter
Counter to keep the active servers.
Client_Acceptor * client_acceptor_
ACE_thread_t creator_
Private Types
enum responseID { ID_CRC_OK = 1,
ID_CRC_ERROR = -1
 }
Basic enum type for error checking.
Member Typedef Documentation
typedef ACE_Svc_Handler<ACE_SOCK_STREAM, ACE_NULL_SYNCH> Client_Handler::inherited
Definition at line 47 of file client_handler.h.
Member Enumeration Documentation
enum Client_Handler::responseID [private]
Enumeration values:
ID_CRC_OK
ID_CRC_ERROR
Definition at line 45 of file client_handler.h.
Constructor & Destructor Documentation
Client_Handler::Client_Handler (void)
Our constructor still doesn't really do anything. We simply initialize the acceptor pointer to `null` and get our current thread id. The static self() method of ACE_Thread will return you a thread id native to your platform.
Definition at line 21 of file client_handler.cpp.
References data, connectionMsgBlock::DATASIZE, and srv_counter.
Client_Handler::~Client_Handler (void) [protected]
We don't really do anything in our destructor but we've declared it to be protected to prevent casual deletion of this object. As I said above, I really would prefer that everyone goes through the destroy() method to get rid of us.
Definition at line 29 of file client_handler.cpp.
References data.
Member Function Documentation
void Client_Handler::client_acceptor (Client_Acceptor * _client_acceptor) [inline, protected]
And since you shouldn't access a member variable directly, neither should you set (mutate) it. Although it might seem silly to do it this way, you'll thank yourself for it later.
Definition at line 158 of file client_handler.h.
References client_acceptor_.
Client_Acceptor* Client_Handler::client_acceptor (void) [inline, protected]
When we get to the definition of Client_Handler we'll see that there are several places where we go back to the Client_Acceptor for information. It is generally a good idea to do that through an accesor rather than using the member variable directly.
Definition at line 150 of file client_handler.h.
References client_acceptor_.
Referenced by concurrency(), open(), and thread_pool().
int Client_Handler::close (u_long flags = 0)
When an ACE_Task<> object falls out of the svc() method, the framework will call the close() method. That's where we want to cleanup ourselves if we're running in either thread-per-connection or thread-pool mode.
Definition at line 89 of file client_handler.cpp.
References destroy().
int Client_Handler::concurrency (void) [protected]
The concurrency() accessor tells us the current concurrency strategy. It actually queries the Client_Acceptor for it but by having the accessor in place, we could change our implementation without affecting everything that needs to know.
Definition at line 39 of file client_handler.cpp.
References client_acceptor(), and Client_Acceptor::concurrency().
Referenced by handle_input(), and open().
void Client_Handler::destroy (void)
The destroy() method is our preferred method of destruction. We could have overloaded the delete operator but that is neither easy nor intuitive (at least to me). Instead, we provide a new method of destruction and we make our destructor protected so that only ourselves, our derivatives and our friends can delete us. It's a nice compromise.
Definition at line 80 of file client_handler.cpp.
References REMOVE_MASK.
Referenced by close().
Contest * Client_Handler::getContest ()
Definition at line 250 of file client_handler.cpp.
References parentContest.
int Client_Handler::handle_close (ACE_HANDLE handle, ACE_Reactor_Mask mask)
When there is activity on a registered handler, the handle_input() method of the handler will be invoked. If that method returns an error code (eg -- -1) then the reactor will invoke handle_close() to allow the object to clean itself up. Since an event handler can be registered for more than one type of callback, the callback mask is provided to inform handle_close() exactly which method failed. That way, you don't have to maintain state information between your handle_* method calls. The <handle> parameter is explained below... As a side-effect, the reactor will also invoke remove_handler() for the object on the mask that caused the -1 return. This means that we don't have to do that ourselves!
Definition at line 110 of file client_handler.cpp.
int Client_Handler::handle_input (ACE_HANDLE handle)
When we register with the reactor, we're going to tell it that we want to be notified of READ events. When the reactor sees that there is read activity for us, our handle_input() will be invoked. The _handleg provided is the handle (file descriptor in Unix) of the actual connection causing the activity. Since we're derived from ACE_Svc_Handler<> and it maintains it's own peer (ACE_SOCK_Stream) object, this is redundant for us. However, if we had been derived directly from ACE_Event_Handler, we may have chosen not to contain the peer. In that case, the <handle> would be important to us for reading the client's data.
Definition at line 135 of file client_handler.cpp.
References concurrency(), creator_, data, connectionMsgBlock::DATASIZE, Thread_Pool::enqueue(), process(), REGISTER_MASK, REMOVE_MASK, thread_pool(), and Client_Acceptor::thread_pool_.
int Client_Handler::open (void * acceptor)
Most ACE objects have an open() method. That's how you make them ready to do work. ACE_Event_Handler has a virtual open() method which allows us to create this overrride. ACE_Acceptor<> will invoke this method after creating a new Client_Handler when a client connects. Notice that the parameter to open() is a void*. It just so happens that the pointer points to the acceptor which created us. You would like for the parameter to be an ACE_Acceptor<>* but since ACE_Event_Handler is generic, that would tie it too closely to the ACE_Acceptor<> set of objects. In our definition of open() you'll see how we get around that.
Definition at line 54 of file client_handler.cpp.
References client_acceptor(), concurrency(), REGISTER_MASK, and Client_Acceptor::thread_per_connection_.
int Client_Handler::process (unsigned char * rdbuf, size_t rdbuf_len) [protected]
This has nothing at all to do with ACE. I've added this here as a worker function which I will call from handle_input(). That allows me to introduce concurrencly in later tutorials with a no changes to the worker function. You can think of process() as application-level code and everything elase as application-framework code.
Definition at line 200 of file client_handler.cpp.
References ID_CRC_ERROR, connectionMsgBlock::isValid(), Contest::logger, Logger::logMsg(), parentContest, Processor::process(), Contest::processor, and srv_counter.
Referenced by handle_input(), and svc().
void Client_Handler::setContest (Contest * curContest)
Definition at line 245 of file client_handler.cpp.
References parentContest.
Referenced by Client_Acceptor::make_svc_handler().
int Client_Handler::svc (void) [protected]
If the Client_Acceptor which created us has chosen a thread-per-connection strategy then our open() method will activate us into a dedicate thread. The svc() method will then execute in that thread performing some of the functions we used to leave up to the reactor.
Definition at line 191 of file client_handler.cpp.
References data, connectionMsgBlock::DATASIZE, and process().
Thread_Pool * Client_Handler::thread_pool (void) [protected]
Likewise for access to the Thread_Pool that we belong to.
Definition at line 46 of file client_handler.cpp.
References client_acceptor(), and Client_Acceptor::thread_pool().
Referenced by handle_input().
Field Documentation
Client_Acceptor* Client_Handler::client_acceptor_ [protected]
Definition at line 172 of file client_handler.h.
Referenced by client_acceptor().
ACE_thread_t Client_Handler::creator_ [protected]
For some reason I didn't create accessor/mutator methods for this. So much for consistency....
This variable is used to remember the thread in which we were created: the `creator` thread in other words. handle_input() needs to know if it is operating in the main reactor thread (which is the one that created us) or if it is operating in one of the thread pool threads. More on this when we get to handle_input().
Definition at line 182 of file client_handler.h.
Referenced by handle_input().
unsigned char* Client_Handler::data [protected]
Definition at line 119 of file client_handler.h.
Referenced by Client_Handler(), handle_input(), svc(), and ~Client_Handler().
ACE_Thread_Mutex Client_Handler::mutex_ [protected]
Definition at line 113 of file client_handler.h.
Contest* Client_Handler::parentContest [protected]
Definition at line 116 of file client_handler.h.
Referenced by getContest(), process(), and setContest().
int Client_Handler::srv_counter [protected]
Definition at line 122 of file client_handler.h.
Referenced by Client_Handler(), and process().
The documentation for this class was generated from the following files:
client_handler.h
client_handler.cpp