connectionMsgBlock Class Reference
#include <connectionmsgblock.h>
Detailed Description
The information that is exchanged between the evalclient and the evalserver programs, is encapsulated in a connectionMsgBlock structure. This structure is of the following form:
partiticipation code (type long long: 8 bytes)
timestamp (type time_t: 4 bytes)
MSISDN (string (not null terminated) : partDetails::MSISDNSIZE, 13 bytes)
prize id (unsigned char: 1 byte)
Checksum of the structure (CRC32 : 4 bytes)
Methods are provided to check for the validity of the structure, and the retrieval of the information inside the block.
Definition at line 38 of file connectionmsgblock.h.
Public Types
enum { DATASIZE = 29,
DATA_WO_CRC = 25,
CRC_OFFSET = 25
 }
These enums give a more insightful view of the data positions inside the block.
Public Methods
connectionMsgBlock (long long code, class partDetails &pd)
This constructor takes the code and the partDetails object, and creates a message block.
connectionMsgBlock (unsigned char *data)
This constructor takes a buffer and creates a message block WITH the right CRC.
~connectionMsgBlock ()
Default destructor, just deallocates memory for the buffer data.
int retrieveCRC ()
Retrieve the CRC from the buffer.
bool isValid ()
Checks for the validity of the message block.
bool operator== (connectionMsgBlock &cmb)
Compares two message blocks.
unsigned char * getData ()
Returns the raw buffer of the message block.
pair< long long, partDetails > getParticipant ()
Returns a pair containing the code (as a long long) and the corresponding partDetails.
pair< string, partDetails > getParticipantStr ()
Returns a pair containing the code (as a string) and the corresponding partDetails.
Private Attributes
CRC_32 crc32
The object used to calculate the CRC of the message block.
unsigned char * data
Pointer to the data holding the message block (size: DATASIZE).
Member Enumeration Documentation
anonymous enum
Enumeration values:
DATASIZE
DATA_WO_CRC
CRC_OFFSET
Definition at line 46 of file connectionmsgblock.h.
Constructor & Destructor Documentation
connectionMsgBlock::connectionMsgBlock (long long code, class partDetails & pd)
This constructor constructs a message block, given the components separetely. It takes the code (long long type) and the partDetails object containing the rest of the data (must be created beforehand). It then puts the data into place and calculates the CRC for the block. The result is a valid connectionMsgBlock object.
Definition at line 20 of file connectionmsgblock.cpp.
References crc32, data, DATA_WO_CRC, DATASIZE, CRC_32::getCRC(), and partDetails::MSISDNSIZE.
connectionMsgBlock::connectionMsgBlock (unsigned char * newdata)
This constructor constructs a message block from the raw data. It takes an existing buffer (without the CRC part) and appends the correct CRC.
Definition at line 53 of file connectionmsgblock.cpp.
References crc32, CRC_OFFSET, data, DATA_WO_CRC, DATASIZE, and CRC_32::getCRC().
connectionMsgBlock::~connectionMsgBlock ()
The destructor has no other purpose than to deallocate the memory used by the buffer.
Definition at line 91 of file connectionmsgblock.cpp.
References data.
Member Function Documentation
unsigned char * connectionMsgBlock::getData ()
Returns the buffer holding the data
Definition at line 82 of file connectionmsgblock.cpp.
References data.
Referenced by operator==().
pair< long long, partDetails > connectionMsgBlock::getParticipant ()
This method returns a pair object containing the code and respective partDetails object of the current connectionMsgBlock object. The code is of type long long.
Definition at line 129 of file connectionmsgblock.cpp.
References data, partDetails::MSISDNSIZE, partDetails::setGiftId(), partDetails::setMSISDN(), and partDetails::setTimestamp().
Referenced by getParticipantStr().
pair< string, partDetails > connectionMsgBlock::getParticipantStr ()
This is similar to getParticipant(). Likewise, it returns a pair object containing the code and respective partDetails object of the current connectionMsgBlock object. This time the code is of type string.
Definition at line 166 of file connectionmsgblock.cpp.
References getParticipant().
Referenced by Processor::process_i().
bool connectionMsgBlock::isValid ()
Validity of the object is checked by calculating the CRC of the data in the buffer and comparing it to the CRC _in_ the buffer. Returns true if these are equal.
Definition at line 113 of file connectionmsgblock.cpp.
References crc32, data, DATA_WO_CRC, CRC_32::getCRC(), and retrieveCRC().
Referenced by Client_Handler::process().
bool connectionMsgBlock::operator== (connectionMsgBlock & cmb)
Compares two connectionMsgBlocks (using the operator==) It compares the buffers AND the crcs of each object. Returns true if the objects are equal.
Definition at line 66 of file connectionmsgblock.cpp.
References data, DATASIZE, getData(), and retrieveCRC().
int connectionMsgBlock::retrieveCRC ()
Retrieves the CRC of the current object, as held in the buffer.
Definition at line 100 of file connectionmsgblock.cpp.
References CRC_OFFSET, and data.
Referenced by isValid(), and operator==().
Field Documentation
CRC_32 connectionMsgBlock::crc32 [private]
Definition at line 40 of file connectionmsgblock.h.
Referenced by connectionMsgBlock(), and isValid().
unsigned char* connectionMsgBlock::data [private]
Definition at line 43 of file connectionmsgblock.h.
Referenced by connectionMsgBlock(), getData(), getParticipant(), isValid(), operator==(), retrieveCRC(), and ~connectionMsgBlock().
The documentation for this class was generated from the following files:
connectionmsgblock.h
connectionmsgblock.cpp