SQLTable< key, data > Class Template Reference
#include <sqltable.h>
Detailed Description
template<class key, class data> class SQLTable< key, data >
This class is one of the most important of the program. It allows a uniform and more or less consistent way of accessing the database independently of the actual information in the tables. It deals with most of the important SQL commands in a consistent way. These include INSERT, UPDATE, DELETE, SELECT. It offers a number of methods to assist programming in most of the usual ways one may call the SQL commands. It is designed to complement the SQLiteConnection class and right now it cannot be used with another adapter.
The class is a templated class. It uses two abstract classes, namely a key class and a data class. The key class is the one that is used as the index of the SQL table. It can be a PRIMARY KEY or not, this is declared on the construction of the object (and the creation of the respective table). The only requirement for the key class is to provide a c_str() method that returns a pointer to a C string (that is null-terminated). As for the data class there are a few requirements as well:
It must provide a method insertString(), which returns the part of the SQL INSERT command, without the key. For example, if the INSERT command would be:
INSERT INTO CODES VALUES('76138768176', 1, '309641768762', 1231444534);
then the insertString() method should return:
1, '309641768762', 1231444534
This should then be used to form the complete INSERT command to be executed.
Likewise, the data class must provide an updateString() to be used when calling UPDATE on the data.
For information reasons only, it may provide a toHTMLString() method, that displays a table row of its data.
Equally important is the existance of two constructors, a dummy that sets a boolean variable `empty` to true, and a constructor that takes as an argument the string representation of the data. The data is first read using a SELECT command, is output in a string as comma-separated values and passed as a parameter to the data class constructor. The constructor should then tokenize the string and use these values to initialize itself. Of course it has to set the empty boolean to false afterwards. It is a generic way and can be used for pretty much any object that can be put in a table.
Definition at line 69 of file sqltable.h.
Public Methods
SQLTable ()
Dummy constructor.
SQLTable (SQLiteConnection *db, const string &tname, const string &iname, const string &ts, vector< string > &fnames, vector< string > &ftypes, vector< string > &indexnames, bool primarykey)
The default constructor.
SQLTable (const SQLTable &source)
Copy constructor, copies a SQLTable object to another.
SQLTable & operator= (const SQLTable &source)
We overload the assignment operator. Basically the same procedure as the copy constructor.
~SQLTable ()
The default destructor.
bool createIndices ()
Creates the indices described in the vector indices.
bool drop ()
Drops the current table from the database.
pair< key, data > selectObject (size_t index)
Returns a key, data pair of the record that exists in the position index.
data selectObject (key val, const string &iname)
Returns the data object of the record where the field iname = val.
map< key, data > * selectObjects (const key &from, const key &to, const string &iname)
Returns a map of <key, data> objects where iname field is in the range (from, to).
map< key, data > * selectObjects (TimePeriod &tp)
Returns a map of <key, data> objects that have timestamps in the period tp.
map< key, data > * selectObjects (TimeStamp &ts, const string &tpprefix, const string &qtyname)
Returns a map of <key, data> objects that their timeperiods include timestamp ts and qtyname != 0.
map< key, data > * selectObjects (vector< key > &objs, const string &iname)
Return a map of <key, data> objects where the field iname, has values from the vector objs.
map< key, data > * selectAllObjects ()
Return a map of <key, data> of all objects.
map< key, data > * selectDistinctObjects (TimePeriod &tp, const string &iname)
Return a map of the UNIQUE objects (using field iname) in the timeperiod tp.
map< key, data > * selectDistinctObjects (const string &iname)
Return a map of all UNIQUE objects (using field iname).
void selectDistinctObjectsMap (ostream &out, TimePeriod &tp, const string &iname)
Write the UNIQUE objects (using field iname) in the timeperiod tp in the stream out as HTML.
void selectDistinctObjectsMap (ostream &out, const string &iname)
Write all UNIQUE objects (using field iname) in the stream out as HTML.
void insertObject (key val, data &obj)
Inserts the object pair (val, obj) in the table.
void insertObjects (map< key, data > &objs)
Inserts the given map of objects in the table.
void updateObject (const key &val, data &obj, const string &iname)
Updates the object where field iname has the value val according to the values of data obj.
void updateObjects (map< key, data > &objs, const string &iname)
Updates the map of objects, using the index field iname.
void deleteObject (key &val, const string &iname)
Deletes the object where field iname has value val.
void deleteObjects (const key &from, const key &to, const string &iname)
Deletes the objects where field iname has values in the range from-to.
void deleteObjects (vector< key > &objs, const string &iname)
Delete the objects where the field iname takes values from the vector objs.
size_t size (key val, const string &iname)
Returns the number of records where field iname has value val.
size_t size (key from, key to, const string &iname)
Returns the number of records where field iname has value in the range from-to.
size_t size (TimePeriod &tp)
Returns the number of records where the field tsname has values in the timeperiod tp.
size_t size (const TimeStamp &ts, const string &tpprefix, const string &qtyname)
Returns the number of records where their timeperiods include timestamp ts and qtyname != 0.
size_t size ()
Return the size of the table.
size_t sizeofDistinctObjects (TimePeriod &tp, const string &iname)
Return the size of UNIQUE objects (using index iname) in the timeperiod tp.
size_t sizeofDistinctObjects (const string &iname)
Return the size of UNIQUE objects (using index iname).
string sumColumn (key from, key to, const string &iname, const string &colname)
Return the sum of field colname of records where field iname is in the range from-to.
string sumColumn (TimePeriod &tp, key val, const string &iname, const string &colname)
Return the sum of field colname of records where field iname is equal to val and in the timeperiod tp.
string sumColumn (const TimeStamp &ts, const string &tpprefix, key val, const string &iname, const string &colname)
Return the sum of field colname of records where field iname is equal to val and their timeperiods include timestamp ts and qtyname != 0.
string sumColumn (key val, const string &iname, const string &colname)
Return the sum of field colname of records where field iname is equal to val.
data operator[] (key x)
Overload the operator[] to access the object where indexname is equal to x.
pair< key, data > operator[] (size_t ind)
Overload the operator[] to access the object in the position ind.
bool isReady ()
Return true if the table is opened and operational.
void logMsg (string msg)
Wrapper around logger object's logMsg.
Private Types
typedef map< key, vector< data > > sqlmap
We typedef the map<key, vector<data> > type to sqlmap.
Private Attributes
bool ready
This boolean declares whether a table is ready to be used.
SQLiteConnection * dbcon
Pointer to the SQLiteConnection object.
string tablename
The name of the table.
string indexname
The name of the key field of the table.
string tsname
The name of the timestamp field.
vector< string > fieldnames
A vector that holds the names of all the fields.
vector< string > fieldtypes
This vector holds the names of the _types)_ of the fields.
vector< string > indices
This vector holds the names of the fields to be indexed.
bool hasPrimaryKey
If true then the index is also a PRIMARY KEY.
Member Typedef Documentation
template<class key, class data> typedef map<key, vector<data> > SQLTable< key, data >::sqlmap [private]
Definition at line 98 of file sqltable.h.
Referenced by SQLTable< key, data >::selectDistinctObjectsMap().
Constructor & Destructor Documentation
template<class key, class data> SQLTable< key, data >::SQLTable () [inline]
Definition at line 102 of file sqltable.h.
template<class key, class data> SQLTable< key, data >::SQLTable< key, data > (SQLiteConnection * db, const string & tname, const string & iname, const string & ts, vector< string > & fnames, vector< string > & ftypes, vector< string > & indexnames, bool primarykey)
This is the constructor. Apart from initializing the member variables dbcon, tablename, indexname, tsname, fieldnames, fieldtypes and hasPrimaryKey, it is responsible to check for the existense of the table and create it if needed. The creation of the table uses the following information:
The key of the table (the first field) is indexname
It is declared as PRIMARY KEY if hasPrimaryKey is set to true
All the fields are created using the names and types in fieldnames and types vectors Upon successfull creation the ready flag is set to true.
template<class key, class data> SQLTable< key, data >::SQLTable (const SQLTable< key, data > & source)
This is the copy constructor, copies the contents of a source SQLTable to another
Definition at line 237 of file sqltable.h.
template<class key, class data> SQLTable< key, data >::~SQLTable () [inline]
Definition at line 117 of file sqltable.h.
Member Function Documentation
template<class key, class data> bool SQLTable< key, data >::createIndices ()
This method creates the necessary indices for the current table, if needed. First it checks for the existence of the indices with existsIndex(). If it exists it does a CREATE INDEX on the table, using a UNIQUE index if the field is a PRIMARY KEY. Upon successfull creation the ready flag is set to true. The indices are VERY important to the performance of the database, esp. with very large datasets.
Definition at line 353 of file sqltable.h.
References SQLTable< key, data >::dbcon, SQLiteConnection::existsIndex(), SQLiteConnection::getdb(), SQLTable< key, data >::hasPrimaryKey, SQLTable< key, data >::indexname, SQLTable< key, data >::indices, SQLTable< key, data >::logMsg(), SQLiteConnection::logTransaction(), and SQLTable< key, data >::tablename.
template<class key, class data> void SQLTable< key, data >::deleteObject (key & val, const string & iname)
Deletes the object where field has value val from the table. The key class is required to provide a c_str() method.
Definition at line 1105 of file sqltable.h.
References SQLTable< key, data >::dbcon, SQLiteConnection::getdb(), SQLTable< key, data >::logMsg(), SQLiteConnection::logTransaction(), SQLiteConnection::reconnect(), and SQLTable< key, data >::tablename.
Referenced by SQLTable< key, data >::deleteObjects().
template<class key, class data> void SQLTable< key, data >::deleteObjects (vector< key > & objs, const string & iname)
Deletes the objects included in the given vector objs from the table. Calls deleteObject() for each object.
Definition at line 1201 of file sqltable.h.
References SQLTable< key, data >::deleteObject(), and SQLTable< key, data >::indexname.
template<class key, class data> void SQLTable< key, data >::deleteObjects (const key & from, const key & to, const string & iname)
Deletes the object where field has value val in the range (from,to). The key class is required to provide a c_str() method.
Definition at line 1156 of file sqltable.h.
References SQLTable< key, data >::dbcon, SQLiteConnection::getdb(), SQLTable< key, data >::logMsg(), SQLiteConnection::logTransaction(), and SQLTable< key, data >::tablename.
template<class key, class data> bool SQLTable< key, data >::drop ()
Drops the table, NOT a destuctor. The destructor should not delete the table from the database.
Definition at line 413 of file sqltable.h.
References SQLTable< key, data >::dbcon, SQLiteConnection::getdb(), SQLTable< key, data >::logMsg(), SQLiteConnection::logTransaction(), and SQLTable< key, data >::tablename.
template<class key, class data> void SQLTable< key, data >::insertObject (key val, data & obj)
Inserts the object (val, obj.insertString()) to the table. The data class is required to provide an insertString() method. The key class is required to provide a c_str() method. The same procedure is followed as in SQLiteConnection::commitTransaction().
Definition at line 1018 of file sqltable.h.
References SQLiteConnection::beginTransaction(), SQLiteConnection::commitTransaction(), SQLiteConnection::conflicts, SQLTable< key, data >::dbcon, SQLiteConnection::getdb(), SQLTable< key, data >::logMsg(), SQLiteConnection::logTransaction(), SQLiteConnection::max_conflicts, SQLiteConnection::reconnect(), SQLTable< key, data >::tablename, SQLiteConnection::transactioncmd, SQLiteConnection::transactions, SQLiteConnection::transactions_enabled, and SQLiteConnection::transactions_threshold.
Referenced by SQLTable< key, data >::insertObjects().
template<class key, class data> void SQLTable< key, data >::insertObjects (map< key, data > & objs)
Inserts the objects (val, obj.insertString()) included in the given map to the table. Calls insertObject() for each object.
Definition at line 1090 of file sqltable.h.
References SQLTable< key, data >::insertObject().
template<class key, class data> bool SQLTable< key, data >::isReady () [inline]
Definition at line 225 of file sqltable.h.
template<class key, class data> void SQLTable< key, data >::logMsg (string msg)
Instead of using directly the logmsg method from the logger object, we wrap it with another one, so that if it (the logger) is not available (at the start or the end of execution) we will still have a logging mechanism available via cout.
Definition at line 1666 of file sqltable.h.
References SQLTable< key, data >::dbcon, SQLiteConnection::logger, and Logger::logMsg().
Referenced by SQLTable< key, data >::createIndices(), SQLTable< key, data >::deleteObject(), SQLTable< key, data >::deleteObjects(), SQLTable< key, data >::drop(), SQLTable< key, data >::insertObject(), SQLTable< key, data >::selectAllObjects(), SQLTable< key, data >::selectDistinctObjects(), SQLTable< key, data >::selectDistinctObjectsMap(), SQLTable< key, data >::selectObject(), SQLTable< key, data >::selectObjects(), SQLTable< key, data >::size(), SQLTable< key, data >::sizeofDistinctObjects(), SQLTable< key, data >::sumColumn(), and SQLTable< key, data >::updateObject().
template<class key, class data> SQLTable< key, data > & SQLTable< key, data >::operator= (const SQLTable< key, data > & source)
This is the assignment operator=, works just like the copy constructor
Definition at line 253 of file sqltable.h.
References SQLTable< key, data >::dbcon, SQLTable< key, data >::fieldnames, SQLTable< key, data >::fieldtypes, SQLTable< key, data >::hasPrimaryKey, SQLTable< key, data >::indexname, SQLTable< key, data >::indices, SQLTable< key, data >::ready, SQLTable< key, data >::tablename, and SQLTable< key, data >::tsname.
]template<class key, class data> pair<key, data> SQLTable< key, data >::operator[] (size_t ind) [inline]
Definition at line 220 of file sqltable.h.
]template<class key, class data> data SQLTable< key, data >::operator[] (key x) [inline]
Definition at line 215 of file sqltable.h.
template<class key, class data> map< key, data > * SQLTable< key, data >::selectAllObjects ()
Returns the map of objects <key, data> of all the records. This one should be used with care, esp. with large databases.
Definition at line 713 of file sqltable.h.
References SQLTable< key, data >::dbcon, SQLiteConnection::getdb(), SQLTable< key, data >::logMsg(), and SQLTable< key, data >::tablename.
template<class key, class data> map< key, data > * SQLTable< key, data >::selectDistinctObjects (const string & iname)
Returns the map of objects <key, data> of the UNIQUE records using the field iname.
Definition at line 820 of file sqltable.h.
References SQLTable< key, data >::dbcon, SQLiteConnection::getdb(), SQLTable< key, data >::logMsg(), and SQLTable< key, data >::tablename.
template<class key, class data> map< key, data > * SQLTable< key, data >::selectDistinctObjects (TimePeriod & tp, const string & iname)
Returns the map of objects <key, data> of the UNIQUE records where the field tsname has values inside the period tp. We check for uniqueness using the field iname.
Definition at line 766 of file sqltable.h.
References SQLTable< key, data >::dbcon, TimePeriod::getBeginTS(), SQLiteConnection::getdb(), TimePeriod::getEndTS(), TimeStamp::getTimeStamp(), SQLTable< key, data >::logMsg(), SQLTable< key, data >::tablename, and SQLTable< key, data >::tsname.
template<class key, class data> void SQLTable< key, data >::selectDistinctObjectsMap (ostream & out, const string & iname)
This does not return anything. Instead we provide a filestream descriptor and it writes an HTML table of the UNIQUE records (using the field iname). The class data is required to provide a toHTMLString() method. The performance is much greater than creating a map of the objects in RAM, and then writing it to disk.
Definition at line 948 of file sqltable.h.
References SQLTable< key, data >::dbcon, SQLiteConnection::getdb(), SQLTable< key, data >::logMsg(), SQLTable< key, data >::sqlmap, and SQLTable< key, data >::tablename.
template<class key, class data> void SQLTable< key, data >::selectDistinctObjectsMap (ostream & out, TimePeriod & tp, const string & iname)
This does not return anything. Instead we provide a filestream descriptor and it writes an HTML table of the UNIQUE records (using the field iname) where their tsname field is inside the timeperiod tp. The class data is required to provide a toHTMLString() method. The performance is much greater than creating a map of the objects in RAM, and then writing it to disk.
Definition at line 878 of file sqltable.h.
References SQLTable< key, data >::dbcon, TimePeriod::getBeginTS(), SQLiteConnection::getdb(), TimePeriod::getEndTS(), TimeStamp::getTimeStamp(), SQLTable< key, data >::logMsg(), SQLTable< key, data >::tablename, and SQLTable< key, data >::tsname.
template<class key, class data> data SQLTable< key, data >::selectObject (key val, const string & iname)
Returns the pair <key, data> of the record where field iname has value val.
Definition at line 487 of file sqltable.h.
References SQLTable< key, data >::dbcon, SQLiteConnection::getdb(), SQLTable< key, data >::logMsg(), and SQLTable< key, data >::tablename.
template<class key, class data> pair< key, data > SQLTable< key, data >::selectObject (size_t index)
Returns the pair <key, data> of the record which is in the position index of the TABLE. Basically it uses the OFFSET parameter in SELECT.
Definition at line 446 of file sqltable.h.
References SQLTable< key, data >::dbcon, SQLiteConnection::getdb(), SQLTable< key, data >::logMsg(), and SQLTable< key, data >::tablename.
Referenced by SQLTable< string, partDetails >::operator[](), and SQLTable< key, data >::selectObjects().
template<class key, class data> map< key, data > * SQLTable< key, data >::selectObjects (vector< key > & objs, const string & iname)
Returns the map of objects <key, data> of the records where the field iname takes values given in the vector<key> objs.
Definition at line 692 of file sqltable.h.
References SQLTable< key, data >::indexname, and SQLTable< key, data >::selectObject().
template<class key, class data> map< key, data > * SQLTable< key, data >::selectObjects (TimeStamp & ts, const string & tpprefix, const string & qtyname)
Returns the pair <key, data> of the record where the given ts is inside the values of the fields {tpprefix}_begin and {tpprefix}_end and where the value of the field qtyname is != 0.
Definition at line 635 of file sqltable.h.
References SQLTable< key, data >::dbcon, SQLiteConnection::getdb(), TimeStamp::getTimeStamp(), SQLTable< key, data >::logMsg(), and SQLTable< key, data >::tablename.
template<class key, class data> map< key, data > * SQLTable< key, data >::selectObjects (TimePeriod & tp)
Returns the pair <key, data> of the record where field tsname (which is used to hold timestamp information) is inside the timeperiod tp.
Definition at line 581 of file sqltable.h.
References SQLTable< key, data >::dbcon, TimePeriod::getBeginTS(), SQLiteConnection::getdb(), TimePeriod::getEndTS(), TimeStamp::getTimeStamp(), SQLTable< key, data >::logMsg(), SQLTable< key, data >::tablename, and SQLTable< key, data >::tsname.
template<class key, class data> map< key, data > * SQLTable< key, data >::selectObjects (const key & from, const key & to, const string & iname)
Returns the pair <key, data> of the record where field iname has value in the range (from, to).
Definition at line 528 of file sqltable.h.
References SQLTable< key, data >::dbcon, SQLiteConnection::getdb(), SQLTable< key, data >::logMsg(), and SQLTable< key, data >::tablename.
template<class key, class data> size_t SQLTable< key, data >::size ()
Returns the number of all records.
Definition at line 1495 of file sqltable.h.
References SQLTable< key, data >::dbcon, SQLiteConnection::getdb(), SQLTable< key, data >::logMsg(), and SQLTable< key, data >::tablename.
template<class key, class data> size_t SQLTable< key, data >::size (const TimeStamp & ts, const string & tpprefix, const string & qtyname)
Returns the number of the records where the given ts is inside the values of the fields {tpprefix}_begin and {tpprefix}_end and where the value of the field qtyname is != 0.
Definition at line 1460 of file sqltable.h.
References SQLTable< key, data >::dbcon, SQLiteConnection::getdb(), TimeStamp::getTimeStamp(), SQLTable< key, data >::logMsg(), and SQLTable< key, data >::tablename.
template<class key, class data> size_t SQLTable< key, data >::size (TimePeriod & tp)
Returns the number of all the records whom the field tsname (which holds timestamp information) is inside the timeperiod tp.
Definition at line 1361 of file sqltable.h.
References SQLTable< key, data >::dbcon, TimePeriod::getBeginTS(), SQLiteConnection::getdb(), TimePeriod::getEndTS(), TimeStamp::getTimeStamp(), SQLTable< key, data >::logMsg(), SQLTable< key, data >::tablename, and SQLTable< key, data >::tsname.
template<class key, class data> size_t SQLTable< key, data >::size (key from, key to, const string & iname)
Returns the number of all the records whom the field iname has value in the range (from, to).
Definition at line 1331 of file sqltable.h.
References SQLTable< key, data >::dbcon, SQLiteConnection::getdb(), SQLTable< key, data >::logMsg(), and SQLTable< key, data >::tablename.
template<class key, class data> size_t SQLTable< key, data >::size (key val, const string & iname)
Returns the number of all the records whom the field iname has value equal to val.
Definition at line 1301 of file sqltable.h.
References SQLTable< key, data >::dbcon, SQLiteConnection::getdb(), SQLTable< key, data >::logMsg(), and SQLTable< key, data >::tablename.
template<class key, class data> size_t SQLTable< key, data >::sizeofDistinctObjects (const string & iname)
Returns the number of all the unique records (using the index iname).
Definition at line 1426 of file sqltable.h.
References SQLTable< key, data >::dbcon, SQLiteConnection::getdb(), SQLTable< key, data >::logMsg(), and SQLTable< key, data >::tablename.
template<class key, class data> size_t SQLTable< key, data >::sizeofDistinctObjects (TimePeriod & tp, const string & iname)
Returns the number of all the unique records (using the index iname) whom the field tsname (whichholds timestamp information) is inside the timeperiod tp.
Definition at line 1393 of file sqltable.h.
References SQLTable< key, data >::dbcon, TimePeriod::getBeginTS(), SQLiteConnection::getdb(), TimePeriod::getEndTS(), TimeStamp::getTimeStamp(), SQLTable< key, data >::logMsg(), SQLTable< key, data >::tablename, and SQLTable< key, data >::tsname.
template<class key, class data> string SQLTable< key, data >::sumColumn (key val, const string & iname, const string & colname)
Returns the sum of the field colname, of all the records for which the file iname is equal to val.
Definition at line 1634 of file sqltable.h.
References SQLTable< key, data >::dbcon, SQLiteConnection::getdb(), SQLTable< key, data >::logMsg(), and SQLTable< key, data >::tablename.
template<class key, class data> string SQLTable< key, data >::sumColumn (const TimeStamp & ts, const string & tpprefix, key val, const string & iname, const string & colname)
Returns the sum of the field colname, of all the records for which the given ts is inside the values of the fields {tpprefix}_begin and {tpprefix}_end and where the value of the field qtyname is != 0.
Definition at line 1592 of file sqltable.h.
References SQLTable< key, data >::dbcon, SQLiteConnection::getdb(), TimeStamp::getTimeStamp(), SQLTable< key, data >::logMsg(), and SQLTable< key, data >::tablename.
template<class key, class data> string SQLTable< key, data >::sumColumn (TimePeriod & tp, key val, const string & iname, const string & colname)
Returns the sum of the field colname, of all the records for which the field iname is equal to val and the field tsname is inside the timeperiod tp.
Definition at line 1555 of file sqltable.h.
References SQLTable< key, data >::dbcon, TimePeriod::getBeginTS(), SQLiteConnection::getdb(), TimePeriod::getEndTS(), TimeStamp::getTimeStamp(), SQLTable< key, data >::logMsg(), SQLTable< key, data >::tablename, and SQLTable< key, data >::tsname.
template<class key, class data> string SQLTable< key, data >::sumColumn (key from, key to, const string & iname, const string & colname)
Returns the sum of the field colname, of all the records for which the field iname has value in the range (from, to).
Definition at line 1523 of file sqltable.h.
References SQLTable< key, data >::dbcon, SQLiteConnection::getdb(), SQLTable< key, data >::logMsg(), and SQLTable< key, data >::tablename.
template<class key, class data> void SQLTable< key, data >::updateObject (const key & val, data & obj, const string & iname)
Updates the object where field iname has value iname, using the values in the object data. The data class is required to provide for an updateString() method. The same procedure is followed as in SQLiteConnection::commitTransaction().
Definition at line 1218 of file sqltable.h.
References SQLiteConnection::beginTransaction(), SQLiteConnection::commitTransaction(), SQLiteConnection::conflicts, SQLTable< key, data >::dbcon, SQLiteConnection::getdb(), SQLTable< key, data >::indexname, SQLTable< key, data >::logMsg(), SQLiteConnection::logTransaction(), SQLiteConnection::max_conflicts, SQLiteConnection::reconnect(), SQLTable< key, data >::tablename, SQLiteConnection::transactioncmd, SQLiteConnection::transactions, SQLiteConnection::transactions_enabled, and SQLiteConnection::transactions_threshold.
Referenced by SQLTable< key, data >::updateObjects().
template<class key, class data> void SQLTable< key, data >::updateObjects (map< key, data > & objs, const string & iname)
Updates the objects (val, obj.updateString()) included in the given map to the table. Calls updateObject() for each object.
Definition at line 1287 of file sqltable.h.
References SQLTable< key, data >::indexname, and SQLTable< key, data >::updateObject().
Field Documentation
template<class key, class data> SQLiteConnection* SQLTable< key, data >::dbcon [private]
Definition at line 74 of file sqltable.h.
Referenced by SQLTable< key, data >::createIndices(), SQLTable< key, data >::deleteObject(), SQLTable< key, data >::deleteObjects(), SQLTable< key, data >::drop(), SQLTable< key, data >::insertObject(), SQLTable< key, data >::logMsg(), SQLTable< key, data >::operator=(), SQLTable< key, data >::selectAllObjects(), SQLTable< key, data >::selectDistinctObjects(), SQLTable< key, data >::selectDistinctObjectsMap(), SQLTable< key, data >::selectObject(), SQLTable< key, data >::selectObjects(), SQLTable< key, data >::size(), SQLTable< key, data >::sizeofDistinctObjects(), SQLTable< key, data >::sumColumn(), and SQLTable< key, data >::updateObject().
template<class key, class data> vector<string> SQLTable< key, data >::fieldnames [private]
Definition at line 86 of file sqltable.h.
Referenced by SQLTable< key, data >::operator=().
template<class key, class data> vector<string> SQLTable< key, data >::fieldtypes [private]
Definition at line 89 of file sqltable.h.
Referenced by SQLTable< key, data >::operator=().
template<class key, class data> bool SQLTable< key, data >::hasPrimaryKey [private]
Definition at line 95 of file sqltable.h.
Referenced by SQLTable< key, data >::createIndices(), and SQLTable< key, data >::operator=().
template<class key, class data> string SQLTable< key, data >::indexname [private]
Definition at line 80 of file sqltable.h.
Referenced by SQLTable< key, data >::createIndices(), SQLTable< key, data >::deleteObjects(), SQLTable< key, data >::operator=(), SQLTable< string, partDetails >::operator[](), SQLTable< key, data >::selectObjects(), SQLTable< key, data >::updateObject(), and SQLTable< key, data >::updateObjects().
template<class key, class data> vector<string> SQLTable< key, data >::indices [private]
Definition at line 92 of file sqltable.h.
Referenced by SQLTable< key, data >::createIndices(), and SQLTable< key, data >::operator=().
template<class key, class data> bool SQLTable< key, data >::ready [private]
Definition at line 71 of file sqltable.h.
Referenced by SQLTable< string, partDetails >::isReady(), SQLTable< key, data >::operator=(), and SQLTable< string, partDetails >::SQLTable().
template<class key, class data> string SQLTable< key, data >::tablename [private]
Definition at line 77 of file sqltable.h.
Referenced by SQLTable< key, data >::createIndices(), SQLTable< key, data >::deleteObject(), SQLTable< key, data >::deleteObjects(), SQLTable< key, data >::drop(), SQLTable< key, data >::insertObject(), SQLTable< key, data >::operator=(), SQLTable< key, data >::selectAllObjects(), SQLTable< key, data >::selectDistinctObjects(), SQLTable< key, data >::selectDistinctObjectsMap(), SQLTable< key, data >::selectObject(), SQLTable< key, data >::selectObjects(), SQLTable< key, data >::size(), SQLTable< key, data >::sizeofDistinctObjects(), SQLTable< key, data >::sumColumn(), and SQLTable< key, data >::updateObject().
template<class key, class data> string SQLTable< key, data >::tsname [private]
Definition at line 83 of file sqltable.h.
Referenced by SQLTable< key, data >::operator=(), SQLTable< key, data >::selectDistinctObjects(), SQLTable< key, data >::selectDistinctObjectsMap(), SQLTable< key, data >::selectObjects(), SQLTable< key, data >::size(), SQLTable< key, data >::sizeofDistinctObjects(), and SQLTable< key, data >::sumColumn().
The documentation for this class was generated from the following file:
sqltable.h