Processor Class Reference
#include <processor.h>
Detailed Description
This class works in exactly the same way as Logger. Its use is slightly different, in that it is called from Client_Handler to process the messages that are sent to the server, calls Day::executeDraw() on the object and returns the result to the handler, which in turn returns it to evalclient and closes the connection.
Definition at line 37 of file processor.h.
Public Methods
Processor (Contest *myContest)
The standard constructor is passed a pointer to the parent Contest object.
virtual ~Processor ()
Typical destructor.
virtual int open (void *)
Virtual open, starts the thread in which the processing takes place.
virtual int close (u_long flags=0)
Closes the thread.
virtual int svc (void)
This method handles the dequeueing of the messages.
ACE_Future< int > process (connectionMsgBlock *cmb)
Process the message, or rather queue it for processing.
int process_i (connectionMsgBlock *cmb)
Actual implementation of the processing method.
Private Attributes
Contest * parentContest
Pointer to the parent Contest object.
ACE_Thread_Mutex mutex_
The mutex mechanism, we use ACE's Guard.
ACE_Activation_Queue activation_queue_
The queue to keep the method objects.
Constructor & Destructor Documentation
Processor::Processor (Contest * contest)
The constructor just initializes the Contest pointer.
Definition at line 18 of file processor.cpp.
Processor::~Processor () [virtual]
Dummy destructor just calls close().
Definition at line 25 of file processor.cpp.
References close().
Member Function Documentation
int Processor::close (u_long flags = 0) [virtual]
Called when the active object is destroyed. A no-op actually.
Definition at line 43 of file processor.cpp.
Referenced by ~Processor().
int Processor::open (void *) [virtual]
The open() method where the active object is activated Create a detached thread to handle the processing.
Definition at line 34 of file processor.cpp.
Referenced by Contest::initProcessor().
ACE_Future< int > Processor::process (connectionMsgBlock * cmb)
This method is called asynchronously. It processes the message It actually creates a future object that will hold the result of the action and puts the method object (of type processor_MO) to the activation_queue_ of the Processor object. This in turn is handled by svc() and the actual processing method process_i() is called to do the processing.
Definition at line 80 of file processor.cpp.
References activation_queue_.
Referenced by Client_Handler::process().
int Processor::process_i (connectionMsgBlock * cmb)
The actual method to do the processing. It keeps everything inside an ACE Guard scope for safety reasons. This one is actually a very important method so we'll do a more thorough analysis:
First the message is converted into a string and is checked in the Participants table if it exists. If so ID_USEDCODE is returned.
If we proceed, we have to know the current day, so we use getCurrentDay() from Contest object.
Increase counter by 1.
We check if this MSISDN has been used in this day already and if so we increase unique_counter as well.
Now that we have a valid partDetails object we call Day::executeDraw on this and we have the result of the draw in the same partDetails object.
If it is a prize, we disable transactions, insert the record in the CODES and WINNINGCODES tables, update the PRIZES table and re-enable the transactions.
We also update the COUNTERS table, do some logging and return the id of the prize to the calling function/method (Client_Handler::svc() actually).
Definition at line 108 of file processor.cpp.
References SQLiteConnection::commitTransaction(), Day::counter, Contest::Counters, Contest::dbconnection, Day::executeDraw(), TimePeriod::getBeginTS(), Contest::getCurrentDay(), connectionMsgBlock::getParticipantStr(), Day::getTimePeriod(), giftDetails::ID_USEDCODE, SQLTable< string, partDetails >::insertObject(), partDetails::isEmpty(), Contest::logger, Logger::logMsg(), parentContest, Contest::Participants, Day::prizes, Contest::Prizes, SQLTable< string, partDetails >::selectObject(), SQLTable< string, partDetails >::size(), TimeStamp::toString(), Day::unique_counter, SQLTable< string, Day >::updateObject(), SQLTable< string, giftDetails >::updateObject(), Day::updateString(), and Contest::Winners.
int Processor::svc (void) [virtual]
The svc() method is the one that does all the work. The thread created will run in an infinite loop waiting for method objects to be enqueued on the private activation queue. Once a method object is inserted in the queue the thread wakes up dequeues the object and then invokes the call() method on the object it just dequeued. If there are no method objects on the activation queue the task blocks and falls asleep.
Definition at line 56 of file processor.cpp.
Field Documentation
ACE_Activation_Queue Processor::activation_queue_ [private]
Definition at line 68 of file processor.h.
Referenced by process().
ACE_Thread_Mutex Processor::mutex_ [private]
Definition at line 65 of file processor.h.
Contest* Processor::parentContest [private]
Definition at line 62 of file processor.h.
Referenced by process_i().
The documentation for this class was generated from the following files:
processor.h
processor.cpp