partdetails.cpp File Reference
#include `partdetails.h`
#include `strtokenizer.h`
Functions
ostream & operator<< (ostream &out, partDetails &pd)
Function Documentation
ostream& operator<< (ostream & out, partDetails & pd)
We overload the operator<< to allow a partDetails object to be output to a C++ stream. The output will be of the form: MSISDN\tGID\tDATESTRING
Definition at line 68 of file partdetails.cpp.
References partDetails::getGiftId(), partDetails::getMSISDN(), partDetails::getTimestamp(), and TimeStamp::toString().